### ISSUE TITLE
Provide easy & working code sample

### ISSUE THREAD

**Issue by sobrienti** [rfussien/leboncoin-crawler#10]
Hey there, 

Stunning work! This API seems to be extremely powerful to get data from LeBonCoin and well documented. 

I have just noticed that it seems like the demo/ folder has not been updated in 2 years; I have also not been able to fetch any ads using the email.php file contained in this folder. So it's possible that the code in this file may need to be improved. It would be a nice addition to have an up to date and working code sample. 

Best,

**Comment by rfussien** [comment]
@sobrienti, thanks for the feedback.

The demo code was still working, even after 2 years without any modification. However the url in this file didn't have ads anymore. I just changed it (_cf commit f6700c6b5cabe12a78a61a5e45914218e0eb69e8_).
