### ISSUE TITLE
AdCrawler doesn't catch picture when there is only one

### ISSUE THREAD

**Issue by JulienMalige** [rfussien/leboncoin-crawler#2]
Hey, 

I don't know if the project is still maintained but I use it and there is a little bug when the Ad contains only one picture (picture array is empty). 

I think that the structure has changed, so if it's ok I will submit a pull request to fix it.

**Comment by rfussien** [comment]
Hi Julien,
I didn't have much time recently, so this project is living by itself. So feel free to submit a pull request with fix and tests, I'll be glad to merge what you've done.
