### ISSUE TITLE
Url from source have changed (no more protocole)

### ISSUE THREAD

**Issue by JulienMalige** [rfussien/leboncoin-crawler#4]
The urls from leboncoin.fr have changed from :
`href="http://www.leboncoin.fr/sports_hobbies/918207998.htm?ca=3_s"`
to 
`href="//www.leboncoin.fr/sports_hobbies/918207998.htm?ca=3_s"`

I will fix it

**Comment by rfussien** [comment]
Hi Julien,
Thanks for the feedback.
I updated the content for the tests and fix the url problem.
I didn't use your merge request as I'm already using the Url package from the phpleague and I'd like to stick to it.
