### ISSUE TITLE
The crawler doesn't work anymore

### ISSUE THREAD

**Issue by oliviermattei** [rfussien/leboncoin-crawler#6]
Hi,

I think the new version of leboncoin change many things.

actually, when i crawl this url, http://www.leboncoin.fr/image_son/offres/provence_alpes_cote_d_azur/occasions/?th=1&q=focal%20aria.

I have 

{
"page": 1,
"links": {
"current": "http://www.leboncoin.fr/image_son/offres/provence_alpes_cote_d_azur/occasions/?q=focal%20aria&o=1",
"previous": "",
"next": ""
},
"total_ads": 0,
"total_page": 0,
"category": "image_son",
"location": null,
"search_area": "toute la france",
"sort_by": "date",
"type": "all",
"ads": []
}

**Comment by rfussien** [comment]
Hi Olivier,

You thought well and I was already aware of the problem.
Unfortunately, I'm afraid I don't have any time to fix it now as I need to rewrite a big part of the package to make it work again.

But feel free to send a fix, it would help and be sincerely appreciated.
